### ISSUE TITLE
Bump buildx to v0.5.1

### ISSUE THREAD

**Issue by gaby** [gabrieldemarmiesse/python-on-whales#147]
Any plans to pump the version of buildx ? Current is 0.5.1

https://github.com/docker/buildx/releases

**Comment by gabrieldemarmiesse** [comment]
Sure, I'll update it.

Note that since Docker 19.03, buildx comes bundled with the CLI (unless the CLI has been downloaded outside a package manager). If you installed the CLI with your package manager and you want to upgrade buildx, follow the installation steps on the https://github.com/docker/buildx#binary-release .

Python-on-whales uses the buildx installed on your system. It will only download it if it's not already present, which is rare. If buildx is already on your system, the version bump in python-on-whales won't affect you.

**Comment by gaby** [comment]
@gabrieldemarmiesse Thank you for the explanation. Looking forward to using this library!
