### ISSUE TITLE
Problem with buildx when using python-on-whales in docker

### ISSUE THREAD

**Issue by sbellem** [gabrieldemarmiesse/python-on-whales#178]
Hi, thanks for this great tool! With the newer version, `0.19.x`, I ran into issues that appear to be related to `buildx`. The current solution I use consists in installing the docker cli in the docker image from the debian repository. Otherwise, when using the `python-on-whales download-cli` command `buildx` is somehow not available.

I'll add more details on how to reproduce the problem as soon as possible.

**Comment by gabrieldemarmiesse** [comment]
Hello! I understand where the problem comes from. Since python-on-whales 0.19, it's up to the user to install buildx. 

Most of the time, it's not an issue because buildx is included in the CLI when installing the CLI from apt-get or other popular managers.

But in some cases (downloading the bare binary) docker buildx is not included and must be installed separately.

I understand that it's inconvenient but the code downloading buildx had some issue and I'm convinced buildx will be included in all CLI packages soon.

For the moment you have to download buildx youself. Here is an example on how to do it with a python image:
```
FROM python:3.9

RUN pip install python-on-whales

RUN python-on-whales download-cli


RUN mkdir -p ~/.docker/cli-plugins && \
    wget https://github.com/docker/buildx/releases/download/v0.5.1/buildx-v0.5.1.linux-amd64 -O ~/.docker/cli-plugins/docker-buildx && \
    chmod a+x ~/.docker/cli-plugins/docker-buildx

RUN python -c 'from python_on_whales import docker; print(docker.buildx.version())'
```

I hope it helps!

**Comment by gabrieldemarmiesse** [comment]
I'll close this issue due to inactivity. Thank you for the feedback!
