### ISSUE TITLE
docker.run with image entrypoint fails

### ISSUE THREAD

**Issue by Arsur** [gabrieldemarmiesse/python-on-whales#179]
Docker images with entrypoints are not working as intended. A command is added as "ENTRYPOINT 'COMMAND' " which always results in an error.
Normal Docker behavior for this is "ENTRYPOINT COMMAND"

Detach is also not working for this image

Another error regarding this it the empty entrypoint flag
Trying to remove the default entrypoint by adding an empty entrypoint="" is not working either. Result is something like: docker run --entrypoint -... -... image

can be reproduced with 
```
test = "m4b-tool merge --output-file=/data/test.m4b --use-filenames-as-chapters --jobs=3 --no-chapter-reindexing --dry-run /data/"
output_generator = docker.run("teardrop/m4b-tool",
                              [test],
                              volumes=[("PATH/data", "/data")],
                              detach=False
                              )

**Comment by gabrieldemarmiesse** [comment]
Hello! I'm not certain I understand everything since I don't use ENTRYPOINT a lot. I'll do my best to follow and make a fix if necessary.

The main command is supposed to be a list of strings, or a single string if there is only one argument.

In the example you give, the correct code would look like this (I tested locally it seems to work):
```python
from python_on_whales import docker

test = ["merge", "--output-file=/data/test.m4b", "--use-filenames-as-chapters", "--jobs=3", "--no-chapter-reindexing",  "--dry-run", "/data/"]
output_generator = docker.run("teardrop/m4b-tool",
                              test,
                              volumes=[("/tmp/data", "/data")],
                              detach=False
                              )
```
Using list of strings is less error-prone than a single string interpreted by bash, this is why this is the default.

Using this new information, does your bug still happen?

**Comment by Arsur** [comment]
I did not read the docs carefully enough. You are right. I also checked the Entrypoint "problem", when passing the command as list I was able to change the entrypoint without problems and even empty entrypoint="" are working.

Thanks for your fast help!
