### ISSUE TITLE
can we push docker images in parallel to the registry?

### ISSUE THREAD

**Issue by vvaisakh2006** [gabrieldemarmiesse/python-on-whales#181]
hello.. does this library support concurrency for pushing images to the registry? 

fyi, the lib looks really cool.. was looking for a way to use buildkit with python..thanks a ton!

**Comment by gabrieldemarmiesse** [comment]
Hello! It's totally possible. You can use multithreading with python-on-whales so you can use a threadpool to push all your images at the same time.
The progress bars might get scrambled though.

One cool thing to do would be to include this threadpool in the push function of python-on-whales so that's it's built-in.

Something like "docker.push("image1", "image2")".

When I have some time I'll implement it.

Note that if you need to push images that you have made with buildkit, you can push them all at once with `docker.buildx.bake(...)` I encourage you to take a look too :)

**Comment by gabrieldemarmiesse** [comment]
I made a pull request and this will allow lists of strings to be passed to the `pull` and `push` functions.

**Comment by vvaisakh2006** [comment]
@gabrieldemarmiesse wow thats super quick...
thanks a ton :) 
and docker.buildx.bake(...) looks super cool too..
