### ISSUE TITLE
'compose' is not a docker command.

### ISSUE THREAD

**Issue by erichamers** [gabrieldemarmiesse/python-on-whales#319]
I'm trying to run `docker.compose.up()`

and I'm getting the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/eric/dev/blueorange/nuskin/localdeploy/venv/lib/python3.9/site-packages/python_on_whales/components/compose/cli_wrapper.py", line 528, in up
    run(full_cmd, capture_stdout=False)
  File "/home/eric/dev/blueorange/nuskin/localdeploy/venv/lib/python3.9/site-packages/python_on_whales/utils.py", line 177, in run
    raise DockerException(
python_on_whales.exceptions.DockerException: The docker command executed was `/usr/bin/docker compose up`.
It returned with code 1
The content of stdout can be found above the stacktrace (it wasn't captured).
The content of stderr is 'docker: 'compose' is not a docker command.
See 'docker --help'
'
```

I actually get this error when running any methods on compose.

**Comment by gabrieldemarmiesse** [comment]
You need to install docker compose v2 :) 

This is easy to do, just follow the instructions there: https://github.com/docker/compose#where-to-get-docker-compose

Can you tell me if that works for you?

**Comment by gaby** [comment]
@gabrieldemarmiesse Is there a way to use compose v1? Compose v2 broke a lot of things in terms of networking. We haven't migrated because of that reason. 

I'd be interesting if this library would allow the developer through a flag specify the compose version, default to to `v2` since thats the latest one. 

Another thing is, when we tested compose we actually installed the binary as "docker-compose", not as a docker plugin. So maybe a config/setting to specify how to call compose would also help.

**Comment by gabrieldemarmiesse** [comment]
This library only support coppose v2 right now. While I believe it's possible to also support v1, I don't have enough time, as maintenainter, to write the code for v1 and maintain it. You are free the fork the codebase and adapt it to support v1, after all, it's an open source project.
