### ISSUE TITLE
Is there a minimum version of Docker required?

### ISSUE THREAD

**Issue by camilovelezr** [gabrieldemarmiesse/python-on-whales#339]
Hello, I cannot find in the docs a minimum version of Docker that needs to be installed. I was wondering if there is indeed a required minimum version of Docker for this library. Thank you!

**Comment by gabrieldemarmiesse** [comment]
Hi, this is a very legitimate question, but the answer is not clear cut.

As python-on-whales have 99% of the time a direct mapping between your function call and the binary call, if you have an old version, you'll be limited to calling functions that are avaiable in your client.
e.g. if you use a very old client, you won't be able to use `docker.buildx.build()` or `docker.build()` (since they both require buildx) but you'll be able to use other functions like `docker.container.inspect()` or `docker.run()`. Same applies to the arguments that you can provide.  

Maybe this would require a specific section in the documentation to explain why there isn't a minimum version.

**Comment by camilovelezr** [comment]
Thank you so much! This makes things very clear.
