### ISSUE TITLE
Run some unit tests with podman in the CI

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [gabrieldemarmiesse/python-on-whales#353]
In our CI we only test python-on-whales with the Docker client. While we won't bend our code to adapt to podman, we should avoid any breakage if it's low effort. To ensure this, we should have some of our tests be executed with both podman and docker.

Ideally we should have a decorator/pytest fixture that we could declare for some specific unit tests and it would run with podman and docker  as two different tests. A bit like `@pytest.mark.parametrize()`.

Note that for this to work, podman should be installed and working in the CI.

**Comment by LewisGaul** [comment]
I can think of a few options here:
1. Automatically parameterise all testcases that use a `DockerClient` instance to run with docker and podman
2. Add a CLI option to the tests to specify to use podman instead of docker
3. Parameterise individual testcases to run with podman as well as docker

The first two options would also need a marker that can be used on testcases that can only be run with one of docker/podman. Effectively, the approach of options 1 and 2 are to blacklist unsupported testcases rather than whitelisting the testcases that should be parameterised.

Thoughts on these options:
- Options 1 and 2 have the advantage of getting good coverage of podman by default
- Option 2 has the advantage of not requiring contributors to have podman set up for the tests to pass, but the corresponding disadvantage that they may hit failures in CI that they don't hit locally by default
- Option 3 has the advantage of simplicity but disadvantage of cluttering individual testcases with boilerplate and making new tests docker-only by default

I think a combination of options 1 and 2 is desirable. We could automatically parameterise all relevant tests but also add a CLI arg to control which parameterisations are used (and could even skip tests automatically based on one of docker/podman not being set up correctly).

This could look something like:
- `pytest tests/` - run tests with docker and podman (or just the one that is detected to be correctly set up)
- `pytest tests/ --ctr-mgr docker` - run tests with docker only
- `pytest tests/ --ctr-mgr podman` - run tests with podman only
- `pytest tests/ --ctr-mgr docker,podman` - explicitly run tests with both docker and podman (for use in the CI)

I have a [project that does something like this](https://github.com/LewisGaul/systemd-containers?tab=readme-ov-file#running-the-tests) (supports specifying docker/podman as a CLI arg, automatically parameterises testcases, and supports controlling parameterisations via CLI args), so I know how to set this up in a neat way with pytest.

The problem with the POW tests is that they generally use a global instance of `DockerClient` rather than using pytest's nice dependency-injection fixture approach. Not wanting to use a hacky approach, this would need changing so that all testcases using a `DockerClient` would take that instance as a fixture argument (which would make parameterisation possible). Using fixtures in this way is good practice anyway so I think would be a positive change, it's just unfortunate that it would need to touch pretty much *every* testcase.

Before I go ahead with making those changes does this all sound ok as an approach?

**Comment by LewisGaul** [comment]
I've put together a demonstration of what I was proposing in a draft PR at https://github.com/gabrieldemarmiesse/python-on-whales/pull/520.

I should rephrase slightly from my previous comment: inidividual testcases are still *opt-in* in the sense they need to switch to using the `ctr_client` parameterised fixture, but they can also switch to using `ctr_client` and then opt out of a parameterisation by specifying which container managers are supported via e.g. `@pytest.mark.ctr_mgr("docker")`.

I plan to move all testcases that use a real container client to use this parameterised fixture, and use the marks to effectively document which functionality is not (yet) supported on other container managers.

@gabrieldemarmiesse could I get your blessing on this approach before going further?

**Comment by gabrieldemarmiesse** [comment]
Cross posting here as it's better for the discussion: 

I was thinking, what is your opinion on marking all xfails with `strict=True`? With this option, we're garanteed that in future, all tests marked as xfails are really failing. We won't have to periodically run pytest with `--runxfail`. If we do a change that fixes one test, we'll have to remove to xfail for the test to pass.

We can actually use 
```
[pytest]
xfail_strict=true
```
to enable it globally.

**Comment by LewisGaul** [comment]
> I was thinking, what is your opinion on marking all xfails with `strict=True`? With this option, we're garanteed that in future, all tests marked as xfails are really failing. We won't have to periodically run pytest with `--runxfail`. If we do a change that fixes one test, we'll have to remove to xfail for the test to pass.
> 
> We can actually use
> 
> ```
> [pytest]
> xfail_strict=true
> ```
> 
> to enable it globally.

I actually assumed this was the default, I'm in favour. (My notes on the option to use `--runxfail` were more for seeing *how* tests are failing for fixing them up).

**Comment by LewisGaul** [comment]
Maybe this can be closed now? :)

**Comment by gabrieldemarmiesse** [comment]
I think we must wrap up a few things before closing this issue to make sure we don't forget any TODOs:
- [ ] `test_tasks.py` doesn't use the docker_client fixture
- [ ] the tests in the `buildx` directory don't use the docker_client fixture.
- [ ] `test_compose.py` doesn't use the docker_client fixture (technically it can't but we should be able to transfer the --docker-exe arg)
- [ ] Enable strict xfail globally.

**Comment by LewisGaul** [comment]
This issue tracks "Run some unit tests with podman in the CI", which is complete - perhaps a separate issue should be created to track the docker client support points you mention?

**Comment by gabrieldemarmiesse** [comment]
Sure that seems reasonnable. Something like "Support cleanly multiple clients in the CI".
