### ISSUE TITLE
Question: Concurrent Docker CLI operations supported?

### ISSUE THREAD

**Issue by gkedge** [gabrieldemarmiesse/python-on-whales#43]
Is there any known concurrency impediments to performing `python-on-whales` commands on threads or processes?

**Comment by gabrieldemarmiesse** [comment]
Hi! It's thread-safe and process-safe :) It's just calling `subprocess` and the docker client in Go behind the scenes so having multiple threads or processes at the same time would be the same as calling concurrently the docker command line interface. 

On the Docker daemon side though, the docker engine handles concurrent requests but you have to make sure that your don't make dangerous scenarios. A very simple one would be:

process 1: start container A in detached mode
...
container A finishes and exits
process 2 (cron in charge of cleaning): runs `docker.container.prune()`
process 1: wants to read the logs of container A but can't because the container was removed.

**Comment by gkedge** [comment]
This is all very good news to us. Attempts to accomplish the same using `docker-py` just caused us unending grief.

I don't know how you handle questions in `Issues`... do you leave them for the curious or figure out how to convey a question into documentation that makes that clear and then close?  I do believe this is an aspect of `python-on-whales` that is worthy of prominent mention if just for the marketing! 

I defer to you to close/handle this "Issue" as you see fit.

**Comment by gabrieldemarmiesse** [comment]
I believe that your question was showing that we lack something in the docs. A small section about multithreading and multiprocessing would be nice. 

I'll keep this issue open until I make a section in the docs about multithreading and multiprocessing.
