### ISSUE TITLE
Error docker.execute with str

### ISSUE THREAD

**Issue by sylvainmouquet** [gabrieldemarmiesse/python-on-whales#463]
Hello,

I have an error when i try to run: 
`docker.execute(vault_server.id, command="vault login -address=http://localhost:8200 myroot")`

> TypeError: When calling docker.execute(), the second argument ('command') should be a list. Here are some examples:docker.execute('somecontainer', ['ls']), docker.execute('somecontainer', ['cat', '/some/file.txt']) In your case, command should not be a string. You can try docker.execute('test-vault-b5d0d7ec-b13d-447f-a60f-185e68555dc4', ['vault', 'login', '-address=http://localhost:8200', 'myroot'], ...).

but in the definition of the execute command, the str should be authorized : 
```

    def execute(
        self,
        container: ValidContainer,
        command: Union[str, List[str]],

```

**Comment by gabrieldemarmiesse** [comment]
Thank you for this issue. Indeed, the type hint do not correspond to what python-on-whales expect. That's a mistake on my part.

We cannot use sh when the user provides a str instead of a list[str] because sh is not available in all containers.

We should change the type hints `Union[str, list[str]]` -> `list[str]` to be clear about what the method expects

**Comment by gabrieldemarmiesse** [comment]
Closing as fixed.
