### ISSUE TITLE
Retrieving Docker Exit Code After `compose.up`

### ISSUE THREAD

**Issue by redheli** [gabrieldemarmiesse/python-on-whales#502]
Hi,

I've been integrating your package into our company CI pipeline and it's been a fantastic tool so far. 

When using the compose.up method, I noticed it doesn't return a Docker instance. Could you advise on how I might retrieve the exit code of a Docker container after executing compose.up? 

```
   docker = DockerClient(
        compose_files=[docker_compose_path],
        compose_compatibility=True,
    )
    docker.compose.up(["my_service"], detach=False)
```

Any guidance or suggestions for handling this would be greatly appreciated.

Thank you!

**Comment by gabrieldemarmiesse** [comment]
I don't think `docker compose up" returns an exit code (it wouldn't make sense since there can be multiple exit code for multiple containers).

What you can do is run some other commands like `docker.compose.ps()` that will list the running containers and then use `docker.container.wait()` to get the exit code. If the container is stopped and not removed, you can also get the exit code by doing `my_container.state.exit_code` (see https://gabrieldemarmiesse.github.io/python-on-whales/docker_objects/containers/)

**Comment by redheli** [comment]
yes, I can get the exit code from `docker.container.wait()`

and as the docker container is detached, I can get realtime logs from 
```
logs = docker.container.logs(container=cont, stream=True, follow=True)
for line in logs:
        text = line[1].decode("utf-8").strip()
        print(f"{text})
```

Thanks man!

**Comment by gabrieldemarmiesse** [comment]
I'm glad that helped :)
